### ISSUE TITLE
No GUI on Wayland

### ISSUE THREAD

**Issue by trinukso** [flathub/com.github.mtkennerly.ludusavi#24]
No GUI on Wayland. On X11 works.

**Comment by mtkennerly** [comment]
Please run this command in a console:

```
flatpak run --env=RUST_BACKTRACE=1 --env=RUST_LOG=debug com.github.mtkennerly.ludusavi
```

Then copy/paste the full output here, and attach a copy of your `~/.var/app/com.github.mtkennerly.ludusavi/config/ludusavi/ludusavi_rCURRENT.log` log file.

**Comment by trinukso** [comment]
Thanks.

https://pastebin.mozilla.org/7i6JFWJB

**Comment by mtkennerly** [comment]
Hmm, I don't see any errors in there. Some questions for you:

* Was there any console output?
* Does the `flatpak` command fail, and if so, what's the exit code? Or does it keep running and just sit there in the console?
* Does Ludusavi show up in the taskbar?
  * If so, what happens if you select it and then use a keyboard shortcut to maximize the window? Depending on your system, it might be `logo + up arrow`, `alt + F10`, or maybe another shortcut.

**Comment by trinukso** [comment]
> Was there any console output?

Anything. Attached a screenshot

> Does Ludusavi show up in the taskbar? 

No window visible... On X11 works.

![Captura desde 2023-06-10 13-03-50](https://github.com/flathub/com.github.mtkennerly.ludusavi/assets/33544668/6de912b1-491f-4ea2-85c0-69c09b3e1293)

**Comment by mtkennerly** [comment]
That's strange. My guess is that this is either a problem in the [Winit](https://github.com/rust-windowing/winit) library or an issue with your graphics drivers.

To narrow it down, would you be willing to try the Winit examples? You would just need to [install Rust](https://rustup.rs/) and then run the following (this tests both the latest version and the version used by Ludusavi):

```
git clone https://github.com/rust-windowing/winit.git
cd winit
cargo run --example resizable

git checkout v0.27.5
cargo run --example resizable
```

Output should look like this:

> <img width="452" alt="image" src="https://github.com/flathub/com.github.mtkennerly.ludusavi/assets/4934192/172669fa-0e1c-4c2b-8a12-35ac6d06c8dd">

**Comment by trinukso** [comment]
None of them work in Wayland.

![1](https://github.com/flathub/com.github.mtkennerly.ludusavi/assets/33544668/480ebb7a-6359-4e44-a20c-2912dae46787)
![2](https://github.com/flathub/com.github.mtkennerly.ludusavi/assets/33544668/234bbda3-1b56-46ec-886d-649821dbb410)

**Comment by mtkennerly** [comment]
Thanks. I took a look through some Winit tickets, and [apparently that's normal](https://github.com/rust-windowing/winit/issues/2247#issuecomment-1091088445) since their examples don't draw anything inside of the window, and Wayland doesn't show the window until something inside is drawn. But there aren't any errors in your console output, so that's good at least.

The next question would be if there's an issue in [Iced](https://github.com/iced-rs/iced). One thing to note is that currently Ludusavi uses Iced with OpenGL, but Iced's next release is dropping OpenGL in favor of WebGPU (plus a software renderer fallback). If we're lucky, maybe those will end up helping here. To test it:

```
git clone https://github.com/iced-rs/iced.git
cd iced
cargo run --package counter

git checkout 0.9.0
cargo run --package counter
cargo run --package counter --features "iced/default_system_font iced/glow iced/tokio"
```

This is how it should look:

> <img width="306" alt="image" src="https://github.com/flathub/com.github.mtkennerly.ludusavi/assets/4934192/175da183-8889-4cb5-b3ce-b14871c56a7e">

**Comment by trinukso** [comment]
Thanks!

![1](https://github.com/flathub/com.github.mtkennerly.ludusavi/assets/33544668/a638c9e7-257b-49b5-96a6-3d14d61fac9c)
![2](https://github.com/flathub/com.github.mtkennerly.ludusavi/assets/33544668/3f214826-a91f-447d-a696-df2906a46664)
![3](https://github.com/flathub/com.github.mtkennerly.ludusavi/assets/33544668/6f215254-de05-4a77-8e86-66a28c188040)

**Comment by mtkennerly** [comment]
Nice! So there's something going wrong with OpenGL specifically, but it'll be fixed by switching to WebGPU before too long. As soon as the next Iced release comes out, I'll update Ludusavi to use it. I'll leave this ticket open in the meantime.

I found some threads talking about the `NoAvailablePixelFormat` error:

* https://github.com/rust-windowing/glutin/issues/913
* https://github.com/rust-windowing/glutin/issues/952

One comment said that it's fixed in Mesa 18.x drivers, but that doesn't seem to be the case for everyone, and some comments suggested that there may be limitations around older hardware and virtual machines.

**Comment by trinukso** [comment]
I don't know, my computer is not old.... Thanks for your attention and work.

![Captura desde 2023-06-11 15-01-18](https://github.com/flathub/com.github.mtkennerly.ludusavi/assets/33544668/53522fd1-4da4-4d0a-995b-a4e47dfa7e9b)
![Captura desde 2023-06-11 15-01-29](https://github.com/flathub/com.github.mtkennerly.ludusavi/assets/33544668/f404f8ac-3289-45f7-80d8-0f4e1d7b1e92)

**Comment by trinukso** [comment]
Cetere... ĉu vi parolas Esperanton? Mi demandas al vi pri tio, pro la nomo de via aplikaĵo. 😅

**Comment by mtkennerly** [comment]
I don't speak it (unfortunately), but I do have an interest in linguistics :) The name comes from Latin `ludus` + Esperanto `savi`. 大学で日本語を勉強したし、at saka sumusubok akong matuto ng Tagalog.

**Comment by trinukso** [comment]
Ha, bone! The Esperanto language has many roots in Latin. That's why I thought about it. Ĝis, kara!

**Comment by trinukso** [comment]
> The name comes from Latin ludus + Esperanto savi.

Do, mi proponas al vi esperantigi la nomon de via aplikaĵo: lud-sav-il-o xD

**Comment by BLACK4585** [comment]
Hey, sorry for writing here again, but seems like I have the same issue.
The window appears, but stays completely black. When I hover over the window, I can see there are some buttons using the changing mouse icon. I'm on Nobara Linux with NVIDIA.
I guess Iced 0.10.0 was already implemented a while ago, so this shouldn't be the error here. Using your command from [above](https://github.com/flathub/com.github.mtkennerly.ludusavi/issues/24#issuecomment-1585477473) doesn't show anything in the console. Is there a way to debug this further, or if this is an error with the NVIDIA driver?

**Comment by mtkennerly** [comment]
@BLACK4585 I think it's normal that there's no console output, since that would be if it crashed outright. Could you send me a copy of `~/.var/app/com.github.mtkennerly.ludusavi/config/ludusavi/ludusavi_rCURRENT.log` after running the command?

If you're willing to install Rust, you could try running the examples from Iced to verify how it behaves in isolation and whether the latest development version behaves better:

```
# latest development version
git clone https://github.com/iced-rs/iced.git
cd iced
cargo run --package counter

# version used by Ludusavi 0.24.3
git checkout 0.12.1
cargo run --package counter
```

**Comment by BLACK4585** [comment]
I just tested the iced examples and they also stay black. I got this error in another app, but sadly I don't remember anymore which app it was.
Here is my log: 
[ludusavi_rCURRENT.log](https://github.com/user-attachments/files/16566254/ludusavi_rCURRENT.log)

**Comment by mtkennerly** [comment]
Hmm, it could be an issue either in your drivers or in [Winit](https://github.com/rust-windowing/winit), but it's hard to say. You could try opening a ticket in the Winit repo and see if they have some idea. That's beyond my area of expertise 😅 

As a workaround, you could try forcing X11 for Ludusavi:

```
flatpak override --nosocket=wayland --socket=x11 com.github.mtkennerly.ludusavi
```

**Comment by BLACK4585** [comment]
Mhh also the workaround doesn't work.
Got some other people testing it and it worked but they are using an AMD card. Maybe the NVIDIA driver is messing up something.

**Comment by mtkennerly** [comment]
Looks like Winit [checks some environment variables](https://github.com/rust-windowing/winit/blob/70c54ee0ff2d174c923e0a74664816a09313b6ee/src/platform_impl/linux/mod.rs#L704-L709) to determine if it should use Wayland. Could you try this?

```
flatpak run --unset-env=WAYLAND_DISPLAY --unset-env=WAYLAND_SOCKET com.github.mtkennerly.ludusavi
```

(It also needs the `DISPLAY` env var to be non-empty in order to use X11, so you may need to add `--env=DISPLAY=:0` or similar.)

**Comment by BLACK4585** [comment]
Also doesn't help, I will ask the Nobara Community once more, I really think this is because of NVIDIA somehow..
Thank you for your help so far!
When I succeed in any way, I will let you know.
